name: EventPRO
favicon: null
layout_spectrum: 0.38718454586341977
typography_spectrum: 0.643312452826649
title: 'EventPRO - Media, Marketing & More'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5427633258514106
  lightness: 0.23473033821210265
  saturation: 0.3924865855369717
  rhythmicContrast: 0.5134952536318451
purpose: []
